### ISSUE TITLE
scale type

### ISSUE THREAD

**Issue by mahyarkarimi** [lopspower/CircularImageView#107]
scale type center inside does not work, it still keeps scale type of center scrop

**Comment by lopspower** [comment]
1) Image 300x300 with:
- **center crop** -> the size of image in circleImageView is 300x300
- **center inside** -> the size of circleImageView is 300x300

2) Image 200x400 with:
- **center crop** -> the size of image in circleImageView is 200x200
- **center inside** -> the size of image in circleImageView is 200x400

So the problem is the size of your image. It must be square and therefore have the same width and height. The scaleType therefore has the same rendering.
