### ISSUE TITLE
[enhancement] civ_circle_color to work with transparent color

### ISSUE THREAD

**Issue by ofir-bar5** [lopspower/CircularImageView#119]
Dear @lopspower , thank you for your great libraries!

I have a drawable which I prefer to have civ_circle_color set to transparent since I only need a circular border.
The "civ_circle_color" already gets its color from the view behind it, in my case, it is some gradient view in which the circular profile image is added on top of that.

Can you please add support for transparent civ_circle_color?

I tried passing transparent values such as #00000000 or @null for civ_circle_color but it didn't work

**Comment by lopspower** [comment]
Hello,
Thank you for your feedback :)

I'm sorry but the technique used to achieve this view does not allow you to do that. 

I started from the principle that if you want a circular image it is that you want it to be cropped in a circular way and therefore you need a background. In your example this is your base image with a circle over it.
For that I advise you rather to use a FrameLayout with your ImageView and another view with a shape border like this:
```xml
<shape xmlns:android="http://schemas.android.com/apk/res/android"
    android:shape="oval">
    <stroke
        android:width="1dp"
        android:color="#78d9ff"/>
</shape>
```

You can otherwise use the properties `civ_circle_color_start` and` civ_circle_color_end` to create a gradient in the background of your image.
